package com.di.jav.autoriacar.model.auto_ria;

import java.util.ArrayList;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
public class All {
    private ArrayList<Object> brandOrigin;
    private ArrayList<Object> marka_id;
    private ArrayList<Object> model_id;
    private ArrayList<Object> s_yers;
    private ArrayList<Object> po_yers;
    private ArrayList<Object> excludeMM;
    private ArrayList<Object> state;
    private ArrayList<Object> city;
    private ArrayList<Object> auto_options;
    private String target;
    private String event;
    private int lang_id;
    private int page;
    private Object limit_page;
    private int countpage;
    private int last_id;
    private int last_search_id;
    private int saledParam;
    private int state_id;
    private int city_id;
    private int state_from;
    private int city_from;
    private ArrayList<Object> m_state;
    private ArrayList<Object> m_city;
    private ArrayList<Object> marka;
    private ArrayList<Object> model;
    private ArrayList<Object> mm_marka;
    private ArrayList<Object> mm_model;
    private ArrayList<Object> mm_marka_filtr;
    private ArrayList<Object> mm_model_filtr;
    private boolean useOrigAutoTable;
    private boolean withoutStatus;
    private boolean with_photo;
    private boolean with_video;
    private int under_credit;
    private int confiscated_car;
    private int with_exchange;
    private ArrayList<Object> exchange_filter;
    private int with_real_exchange;
    private boolean old_only;
    private int user_id;
    private int person_id;
    private boolean with_discount;
    private String auto_id_str;
    private int black_user_id;
    private int order_by;
    private boolean is_online;
    private boolean last_send_id;
    private boolean withoutCache;
    private boolean with_last_id;
    private int color;
    private int color_id;
    private int gear_id;
    private int gearbox;
    private int top;
    private int drive_type;
    private int country;
    private ArrayList<Object> mm_country;
    private ArrayList<Object> mm_country_exeption;
    private int currency;
    private int currency_id;
    private ArrayList<Object> currencies_arr;
    private int auto_repairs;
    private int power_name;
    private int powerFrom;
    private int powerTo;
    private ArrayList<Object> hide_black_list;
    private int fuelRateFrom;
    private int fuelRateTo;
    private int custom;
    private int damage;
    private ArrayList<Object> body_id;
    private ArrayList<Object> bodyStyleId;
    private int type;
    private int metallic;
    private int engineVolumeFrom;
    private int engineVolumeTo;
    private int raceFrom;
    private int raceTo;
    private int sid;
    private int star_auto;
    private String start_date;
    private int drive_id;
    private int door;
    private int price_ot;
    private int price_do;
    private int year;
    private int category_id;
    private int auto_ids_search_position;
    private int print_qs;
    private int last_auto_id;
    private int is_hot;
    private int deletedAutoSearch;
    private int can_be_checked;
    private int seatsFrom;
    private int seatsTo;
    private int wheelFormulaId;
    private int axleId;
    private int carryingTo;
    private int carryingFrom;
    private int company_id;
    private int company_type;
    private int matched_country;
    private String q;
    private ArrayList<Object> bodystyle;
    private Object sellerType;
    private Object purpose;
    private Object _class;
}
